askfm/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_view
from . import views as core_view

app_name = 'accounts'

urlpatterns = [
  url(r'^login/$', auth_view.LoginView.as_view(template_name='accounts/login.html'), name='login'),
  url(r'^logout/$', auth_view.LogoutView.as_view(), name='logout'),
  url(r'^signup/$', core_view.Signup.as_view(), name='signup'),
  url(r'^profile/(?P<pk>\d+)$', core_view.my_profile, name='my_profile'),
  url(r'^edit-profile/(?P<pk>\d+)$', core_view.Edit_profile.as_view(), name='edit_profile'),
  url(r'my-friends/$', core_view.get_friends, name='get_friends'),
  url(r'^follow/(?P<pk>\d+)/$', core_view.follow, name='follow'),
  url(r'^unfollow/(?P<pk>\d+)/$', core_view.unfollow, name='unfollow'),
]

askfm/question/urls.py
from django.conf.urls import url
from . import views

app_name = 'question'

urlpatterns = [
  url(r'^home$', views.home, name='home'),
  url(r'^ans_quest/(?P<pk>\d+)$', views.AnsQuestion.as_view(), name='Ans_question'),
  url(r'^del/(?P<pk>\d+)$', views.quest_del, name='quest_del'),
  url(r'^question$', views.quest, name='quest'),
  url(r'^like_question/(?P<pk>\d+)/$', views.like_question, name='like_question'),
  url(r'^dislike_question/(?P<pk>\d+)/$', views.dislike_question, name='dislike_question'),
  url(r'^add_question/(?P<pk>\d+)/$', views.add_question, name='add_question'),
  url(r'^re_ask_question/(?P<pk>\d+)/$', views.reAsk_question, name='re_ask_question'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from .views import root


urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('askfm.accounts.urls')),
  path('', root, name='root'),
  path('', include('askfm.question.urls')),
  url(r'^oauth/', include('social_django.urls', namespace='social')),
  path('tinymce/', include('tinymce.urls')),
  url('avatar/', include('avatar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

askfm/accounts/models.py
from django.contrib.auth.models import User, PermissionsMixin
from django.db import models


class User(User, PermissionsMixin):
  image = models.ImageField(upload_to='user_images/%Y/%m/%d', blank=True)

  def __str__(self):
    return "{}".format(self.username)


class Friendship(models.Model):
  created = models.DateTimeField(auto_now_add=True, editable=False)
  creator = models.ForeignKey(User, related_name="friendship_creators", on_delete=models.CASCADE)
  friend = models.ForeignKey(User, related_name="friends", on_delete=models.CASCADE)

askfm/accounts/forms.py
from .models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):

  class Meta:
    model = User
    fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'image')

    def __init__(self, *args, **kwargs):
      super().__init__(*args, **kwargs)


class EditProfileForm(forms.ModelForm):
  username = forms.CharField(required=True)
  email = forms.EmailField(required=True)
  first_name = forms.CharField(required=True)
  last_name = forms.CharField(required=True)

  class Meta:
    model = User
    fields = ('username', 'first_name', 'last_name', 'email', 'image')

  def __init__(self, *args, **kwargs):
    super(EditProfileForm, self).__init__(*args, **kwargs)
    self.fields['username'].widget.attrs['readonly'] = True

  def clean_email(self):
    email = self.cleaned_data.get('email')
    username = self.cleaned_data.get('username')

    if email and User.objects.filter(email=email).exclude(username=username).count():
      raise forms.ValidationError('This email address is already in use. Please supply a different email address.')
    return email

askfm/accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.shortcuts import render, redirect
from ..question.models import Question, Like
from .models import User, Friendship
from .forms import EditProfileForm, UserCreateForm
from django.views.generic import UpdateView


# friends page
def get_friends(request):
  current_user = User.objects.get(username=request.user)
  my_friends = Friendship.objects.filter(creator=current_user)
  friends = []
  for friend in my_friends:
    u = User.objects.get(username=friend.friend)
    friends.append(u)
  users = User.objects.all()
  unfriend_users = []
  for u in users:
    if u not in friends:
      unfriend_users.append(u)

  context = {
    'users': unfriend_users,
    'friends': friends,
    'current_user': current_user,
  }
  return render(request, 'accounts/friends.html', context)


# edit user profile
class Edit_profile(UpdateView):
  form_class = EditProfileForm
  template_name = 'accounts/edit_profile.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    users = User.objects.all()
    current_user = User.objects.get(username=self.request.user)
    my_friends = Friendship.objects.filter(creator=current_user)
    friends = []
    for friend in my_friends:
      u = User.objects.get(username=friend.friend)
      friends.append(u)
    unfriend_users = []
    for u in users:
      if u not in friends:
        unfriend_users.append(u)
    context['users'] = unfriend_users
    context['current_user'] = current_user
    return context

  def get_success_url(self):
    return reverse_lazy('accounts:my_profile', kwargs={'pk': self.kwargs['pk']})

  def get_object(self, queryset=None):
    obj = User.objects.get(id=self.kwargs['pk'])
    return obj


def my_profile(request, pk):
  user = User.objects.filter(id=pk)[0]
  questions = Question.objects.filter(status=True, receiver=user)
  likes = []
  like_count = 0
  quest_count = len(questions)
  for question in questions:
    like = Like.objects.filter(user=request.user, question=question)
    if like:
      likes.append(1)
      like_count += 1
    else:
      likes.append(0)
  mylist = zip(questions, likes)
  current_user = User.objects.get(username=request.user)

  your_friend = False
  friends = Friendship.objects.filter(creator=current_user)
  for ff in friends:
    if ff.friend == user:
      your_friend = True

  flag = True
  if user == current_user:
    flag = False

  context = {
    'your_friend': your_friend,
    'flag': flag,
    'questions': mylist,
    'like_count': like_count,
    'quest_count': quest_count,
    'user': user,
    'current_user': current_user,
  }

  return render(request, 'accounts/profile.html', context)


class Signup(CreateView):
  form_class = UserCreateForm
  success_url = reverse_lazy('accounts:login')
  template_name = 'accounts/signup.html'


def follow(request, pk):
  creator = User.objects.get(username=request.user)
  friend = User.objects.get(pk=pk)
  frindship = Friendship.objects.get_or_create(creator=creator, friend=friend)

  # redirect to the same page user in
  return redirect(request.META.get('HTTP_REFERER'))


def unfollow(request, pk):
  creator = User.objects.get(username=request.user)
  friend = User.objects.get(pk=pk)
  friendship = Friendship.objects.filter(creator=creator, friend=friend)
  friendship.delete()
  return redirect(request.META.get('HTTP_REFERER'))

askfm/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}
<style>
  input[name='username']{
    border: none;
    outline: none;
    font-size: 25px;
    text-align: center;
    color: #FF643C;
  }
</style>
{% block title %}
  Feed | AskFm
{% endblock %}

{% block content %}
  <div style="background-color: white; text-align: center">
    <h2 style="padding-top: 20px; color: #FF643C">Edit your profile</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
        <p>
          <h5 style="margin: 0; padding: 0;">{{ field.label_tag }}</h5>
          {{ field}}
          {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        </p>
      {% endfor %}
      <button type="submit">
        <i class="fas fa-location-arrow"></i>
      </button>
    </form>
    <br>
  </div>
{% endblock %}

{% block sideContent %}
  {% include 'question/sideContent.html' %}
{% endblock %}

askfm/accounts/templates/accounts/friends.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Feed | AskFm
{% endblock %}


{% block content %}
  <br>
  <label style="width: 8%"><i style="font-size: 40px;" class="fas fa-search"></i></label>
  <input placeholder="search your friends by keywords"
         style="width: 90%; font-size: 20px;padding: 10px;" type="search" name="search_input">
  <br><br>
  <h5 style="color: #929497">your Friends</h5>
 {% for u in friends %}
    <div class="sid_user">
      <a style="text-decoration: none;" href="{% url 'accounts:my_profile' u.pk %}">
        <span style="margin-left: 20px;">
          <img src="{% if u.image %}
                      {{ u.image.url }}
                    {% else %}
                      {% static 'imgs/default.jpg' %}
                    {% endif %}" style="width: 50px; height: 50px; border-radius: 50%;">
        </span>
        <span style="padding: 20px; font-size: 20px;color: #929497">{{u.username}}</span>
      </a>
      <a href="{% url 'accounts:unfollow' u.pk %}" title="unfollow" class="ask_user">
        <i class="fas fa-user-minus"></i>
      </a>
      <a class="ask_user" href="{% url 'question:add_question' u.pk %}">Ask ></a>
    </div>
  {% endfor %}
{% endblock %}

{% block sideContent %}
  {% include 'question/sideContent.html' %}
{% endblock %}

{% block js %}
  <script>
    let container = document.getElementsByClassName('col-md-8')[0];
    container.style.backgroundColor = 'white';
    $(document).ready(function(){
      let x = $('.nn i');
      for(let i = 0 ; i < x.length; i++)
      {
        $(x[i]).removeClass("active");
      }
      $(x[3]).addClass("active");
    });
    </script>
{% endblock %}

askfm/accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>login AskFm Website</title>
  <!-- font awsome -->
  <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/all.css'
        integrity='sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU'
        crossorigin='anonymous'>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/style_accounts.css' %}">
</head>
<body style="background-color: #2F353A">
  <div class="container">
    <div class="row login-head">
      <div class="col-md-8" style="margin: auto">
        <div class="row">
          <div class="col-md-3">
            <h1><a href="{% url 'root' %}">
                <strong style="font-size: 40px;color: #FF643C;">ask</strong>fm
            </a></h1>
          </div>
          <div class="col-md-6" style="display: inline-block">
            <p>Log in</p>
          </div>
          <div class="col-md-3">
             <a href="{% url 'accounts:signup' %}" class="sig">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr style="border: .2px solid #000000; margin: 10px 0">
  <br>
  <div class="container">
    <div class="row">
      <div class="col-md-8 login-form">
      {% if form.errors %}
        <p style="color: red;">Your username and password didn`t match</p>
      {% endif %}
      <form method="post">
        {% csrf_token %}
        <input type="hidden", name="next" value="{{ next }}"/>
        {% for field in form %}
          <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% for error in field.errors %}
              <p style="color: red;">{{ error }}</p>
            {% endfor %}
            {% if field.help_text %}
              <p><small style="color: gray;">{{ field.help_text }}</small></p>
            {% endif %}
          </p>
        {% endfor %}
        <button type="submit">Login</button>
      </form>
      <br><br>
      <span style="margin-left: 85px">______________________</span>
      <span>Login With</span>
      <span>______________________________</span><br>
      <div>
        <ul style="list-style-type: none; margin-top: 20px; height: 120px;">
          <li style="float: left; margin-right: 10px;">
            <a class="btn btn-outline-dark" href="{% url 'social:begin' 'github' %}">
              <i class="fab fa-github"></i>
            </a>
          </li>
          <li style="float: left; margin-right: 10px;">
            <a class="btn btn-outline-primary" href="{% url 'social:begin' 'facebook' %}">
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
          <li style="float: left; margin-right: 10px;">
            <a class="btn btn-outline-secondary" href="{% url 'social:begin' 'google-oauth2' %}">
              <i class="fab fa-google"></i>
            </a>
          </li>
          <li style="float: left; margin-right: 10px;">
            <a class="btn btn-outline-danger" href="{% url 'social:begin' 'instagram' %}">
              <i class="fab fa-instagram"></i>
            </a>
          </li>
          <li style="float: left;">
            <a class="btn btn-outline-info" href="{% url 'social:begin' 'twitter' %}">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
    </div>
  </div>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

askfm/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Feed | AskFm
{% endblock %}

{% block profile_content %}
  <div id="topimge" style="margin: 20px 0 40px 0; border-radius: 50px;">
    <span style="padding-left: 50px;">
     <img src="{% if user.image %}
                 {{ user.image.url }}
               {% else %}
                 {% static 'imgs/default.jpg' %}
               {% endif %}" style="width: 100px; height: 100px; border-radius: 50%;">
    </span>
    <h1 style="padding-top:10px;margin: 30px 20px 20px 50px;margin-top: 30px;display: inline-block;
      font-size: 50px;color: white;">{{ user.first_name }} {{ user.last_name }}</h1>
    <span><i style="color: green;" class="fas fa-circle"></i></span>

    {% if flag %}
      {% if your_friend %}
        <a href="{% url 'accounts:unfollow' user.pk %}" title="unfollow" style="color: white;float: right;font-size: 40px;margin: 40px;">
          <i name="unfollow" class="fas fa-user-minus"></i>
        </a>
      {% else %}
        <a href="{% url 'accounts:follow' user.pk %}" title="follow" style="color: white;float: right;font-size: 40px;margin: 40px;">
          <i name="follow" class="fas fa-user-plus"></i>
        </a>
      {% endif %}
    {% endif %}
    <br><br>
  </div>
  <!--<hr style="border: 7px solid #CEC4D7; margin: 20px 0">-->
{% endblock %}

{% block content %}

 {% for q in questions %}
    <div class="con">
      <h3 style="padding: 20px;">{{q.0.body}}</h3>
      <br>
      <span style="padding: 20px; font-size: 20px; color: #CEC4D7">
        {{q.0.publish|timesince}}
      </span>
      <br>
      <h4 style="padding: 20px;">{{q.0.answer}}</h4>
      <div style="height: 50px;">
      {% if q.1 == 1 %}
        <a class="like_dis" href="{% url 'question:dislike_question' q.0.id %}" >
          <span style="margin-left: 20px; font-size: 36px; color: #FF643C;">
            <i class='fas fa-heart'></i>
          </span>
        </a>
      {% else %}
        <a title="Like" class="like_dis" href="{% url 'question:like_question' q.0.id %}" >
          <span style="margin-left: 20px; font-size: 36px; color: #CEC4D7;">
            <i class='fas fa-heart'></i>
          </span>
        </a>
      {% endif %}
       <a title="Re ask" style="float: right" href="{% url 'question:re_ask_question' q.0.id %}">
          <span style=" float: right; margin-right: 20px; font-size: 36px; color: #CEC4D7;">
            <i class='fas fa-recycle'></i>
          </span>
       </a>
      </div>
      <hr style="border: 7px solid #CEC4D7; margin: 0">
    </div>
  {% endfor %}
{% endblock %}

{% block sideContent %}
  <div class="row" style="color: white;text-align: center;font-size: 20px;">
    <div style="width: 30%;display: inline">
      <div style="color: #00AEB8;">
        <i class="fas fa-comment-alt" style="font-size: 30px;"></i>
      </div>
      <div>{{ quest_count }}</div>
      <div style="color: #929497;">Posts</div>
    </div>
    <div style="width: 30%; display: inline;">
      <div style="color: #FF643C;">
        <i class="fab fa-gratipay" style="font-size: 30px;"></i>
      </div>
      <div>{{ like_count }}</div>
      <div style="color: #929497;">Likes</div>
    </div>
    <div style="width: 30%; display: inline;">
      <div style="color: #8E008B;">
        <i class="fas fa-user-check" style="font-size: 30px;"></i>
      </div>
      <div>{{ quest_count }}</div>
      <div style="color: #929497;">Followers</div>
    </div>
  </div>
  <br>
  <div class="row" style="color: white;">
    <div style="width: 50%; text-align: center;">
      <h4>About Me</h4>
    </div>
    {% if request.user.pk == user.pk %}
      <div style="width: 50%; text-align: center">
        <a style="color: #FF643C; text-decoration: none;" href="{% url 'accounts:edit_profile' user.pk %}">
          <i class="fas fa-pencil-alt"></i>Edit Profile</a>
      </div>
    {% endif %}
    <div style="width:100%;">
      <label style="padding-left: 20px; font-size: 20px;">username:-  </label>
      <h4 style="display: inline-block;color: #929497;"> {{ user.username }}</h4>
    </div>
    <div style="width:100%;">
      <label style="padding-left: 20px; font-size: 20px;">first name:-  </label>
      <h4 style="display: inline-block;color: #929497;"> {{ user.first_name }}</h4>
    </div>
    <div style="width:100%;">
      <label style="padding-left: 20px; font-size: 20px;">last name:-  </label>
      <h4 style="display: inline-block;color: #929497;"> {{ user.last_name }}</h4>
    </div>
    <div style="width:100%;">
      <label style="padding-left: 20px; font-size: 20px;">email:-  </label>
      <h4 style="display: inline-block;color: #929497;"> {{ user.email }}</h4>
    </div>
  </div>
  <br><br>
  <hr style="border: 1px solid #CEC4D7; margin: 0">
  <br><br>
  <div class="row footer">
    <ul style="list-style: none;margin: 0;padding: 5px; font-size: 30px;">
      <li style="float: left;margin-left: 10px;">
        <a href="https://www.facebook.com/askfmpage">
          <i style="color: #FF643C;" class="fab fa-facebook-f"></i>
        </a>
      </li>
      <li style="float: left;margin-left: 10px;">
        <a href="https://instagram.com/askfm">
          <i style="color: #FF643C;" class="fab fa-instagram"></i>
        </a>
      </li>
      <li style="float: left;margin-left: 10px;">
        <a href="https://twitter.com/askfm">
          <i style="color: #FF643C;" class="fab fa-twitter"></i>
        </a>
      </li>
      <li style="float: left;margin-left: 10px;">
        <a href="https://vk.com/askfm">
          <i style="color: #FF643C;padding: 5px;" class="fab fa-vk"></i>
        </a>
      </li>
      <li style="float: left;margin-left: 10px;color: #929497;">© Ask.fm 2018</li>
    </ul>
  </div>
{% endblock %}

{% block js %}
  <script>
    let topdiv = document.getElementById('topimge');
    topdiv.style.backgroundImage = 'url("../../static/imgs/background.svg")';
    $(document).ready(function(){
      let x = $('.nn i');
      for(let i = 0 ; i < x.length; i++)
      {
        $(x[i]).removeClass("active");
      }
      $(x[2]).addClass("active");
    });
    </script>
{% endblock %}

askfm/accounts/templates/accounts/signup.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>login AskFm Website</title>
  <!-- font awsome -->
  <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/all.css'
        integrity='sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU'
        crossorigin='anonymous'>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/style_accounts.css' %}">
</head>
<body style="background-color: #2F353A">
  <div class="container">
    <div class="row login-head">
      <div class="col-md-8" style="margin: auto">
        <div class="row">
          <div class="col-md-3">
            <h1><a href="{% url 'root' %}">
                <strong style="font-size: 40px;color: #FF643C;">ask</strong>fm
            </a></h1>
          </div>
          <div class="col-md-6" style="display: inline-block">
            <p>Sign up</p>
          </div>
          <div class="col-md-3">
             <a href="{% url 'accounts:login' %}" class="sig">Log in</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr style="border: .2px solid #000000; margin: 10px 0">
  <br>
   <div class="container">
    <div class="row">
      <div class="col-md-8 login-form">
      <br><br>
      <span style="margin-left: 85px">
        _________________________Sign up With___________________________
      </span><br>
      <div>
        <ul style="list-style-type: none; margin-top: 20px; height: 120px;">
          <li style="float: left; margin-right: 10px;">
            <a class="btn btn-outline-dark" href="{% url 'social:begin' 'github' %}">
              <i class="fab fa-github"></i>
            </a>
          </li>
          <li style="float: left; margin-right: 10px;">
            <a class="btn btn-outline-primary" href="{% url 'social:begin' 'facebook' %}">
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
          <li style="float: left; margin-right: 10px;">
            <a class="btn btn-outline-secondary" href="{% url 'social:begin' 'google-oauth2' %}">
              <i class="fab fa-google"></i>
            </a>
          </li>
          <li style="float: left; margin-right: 10px;">
            <a class="btn btn-outline-danger" href="{% url 'social:begin' 'instagram' %}">
              <i class="fab fa-instagram"></i>
            </a>
          </li>
          <li style="float: left;">
            <a class="btn btn-outline-info" href="{% url 'social:begin' 'twitter' %}">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
        </ul>
      </div>
      <span style="margin-left: 85px">
        ____________________________OR________________________________
      </span><br>
      {% if form.errors %}
        <p style="color: red;">Your username and password didn`t match</p>
      {% endif %}
      <form method="post" class="signup-form" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
          <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
              <br><small style="color: grey;">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
        {% endfor %}
        <button type="submit">Sign up</button>
      </form>
    </div>
    </div>
  </div>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>
</html>