askfm/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_view
from . import views as core_view

app_name = 'accounts'

urlpatterns = [
  url(r'^login/$', auth_view.LoginView.as_view(template_name='accounts/login.html'), name='login'),
  url(r'^logout/$', auth_view.LogoutView.as_view(), name='logout'),
  url(r'^signup/$', core_view.Signup.as_view(), name='signup'),
  url(r'^profile/(?P<pk>\d+)$', core_view.my_profile, name='my_profile'),
  url(r'^edit-profile/(?P<pk>\d+)$', core_view.Edit_profile.as_view(), name='edit_profile'),
  url(r'my-friends/$', core_view.get_friends, name='get_friends'),
  url(r'^follow/(?P<pk>\d+)/$', core_view.follow, name='follow'),
  url(r'^unfollow/(?P<pk>\d+)/$', core_view.unfollow, name='unfollow'),
]

askfm/question/urls.py
from django.conf.urls import url
from . import views

app_name = 'question'

urlpatterns = [
  url(r'^home$', views.home, name='home'),
  url(r'^ans_quest/(?P<pk>\d+)$', views.AnsQuestion.as_view(), name='Ans_question'),
  url(r'^del/(?P<pk>\d+)$', views.quest_del, name='quest_del'),
  url(r'^question$', views.quest, name='quest'),
  url(r'^like_question/(?P<pk>\d+)/$', views.like_question, name='like_question'),
  url(r'^dislike_question/(?P<pk>\d+)/$', views.dislike_question, name='dislike_question'),
  url(r'^add_question/(?P<pk>\d+)/$', views.add_question, name='add_question'),
  url(r'^re_ask_question/(?P<pk>\d+)/$', views.reAsk_question, name='re_ask_question'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from .views import root


urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('askfm.accounts.urls')),
  path('', root, name='root'),
  path('', include('askfm.question.urls')),
  url(r'^oauth/', include('social_django.urls', namespace='social')),
  path('tinymce/', include('tinymce.urls')),
  url('avatar/', include('avatar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

askfm/accounts/models.py
from django.contrib.auth.models import User, PermissionsMixin
from django.db import models


class User(User, PermissionsMixin):
  image = models.ImageField(upload_to='user_images/%Y/%m/%d', blank=True)

  def __str__(self):
    return "{}".format(self.username)


class Friendship(models.Model):
  created = models.DateTimeField(auto_now_add=True, editable=False)
  creator = models.ForeignKey(User, related_name="friendship_creators", on_delete=models.CASCADE)
  friend = models.ForeignKey(User, related_name="friends", on_delete=models.CASCADE)

askfm/question/models.py
from django.db import models
from django.utils import timezone
from ..accounts.models import User


# Question Model
class Question(models.Model):

  sender = models.ForeignKey(User, related_name='senders', on_delete=models.CASCADE)
  body = models.TextField()
  receiver = models.ForeignKey(User, related_name='recievers', on_delete=models.CASCADE)
  answer = models.TextField(default='', blank=True)
  publish = models.DateTimeField(default=timezone.now)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)
  status = models.BooleanField(default=False)
  likes = models.IntegerField(default=0)

  class Meta:
    ordering = ('-updated',)

  def __str__(self):
    return str(self.id)


# Like Model
class Like(models.Model):

  user = models.ForeignKey(User, related_name='user_likes', on_delete=models.CASCADE)
  question = models.ForeignKey(Question, related_name='liked_questions', on_delete=models.CASCADE)
  value = models.BooleanField(default=False)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)

  def __str__(self):
    return str(self.user) + ':' + str(self.question) + ':' + str(self.value)

askfm/accounts/forms.py
from .models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):

  class Meta:
    model = User
    fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'image')

    def __init__(self, *args, **kwargs):
      super().__init__(*args, **kwargs)


class EditProfileForm(forms.ModelForm):
  username = forms.CharField(required=True)
  email = forms.EmailField(required=True)
  first_name = forms.CharField(required=True)
  last_name = forms.CharField(required=True)

  class Meta:
    model = User
    fields = ('username', 'first_name', 'last_name', 'email', 'image')

  def __init__(self, *args, **kwargs):
    super(EditProfileForm, self).__init__(*args, **kwargs)
    self.fields['username'].widget.attrs['readonly'] = True

  def clean_email(self):
    email = self.cleaned_data.get('email')
    username = self.cleaned_data.get('username')

    if email and User.objects.filter(email=email).exclude(username=username).count():
      raise forms.ValidationError('This email address is already in use. Please supply a different email address.')
    return email

askfm/question/forms.py
from django import forms
from .models import Question


class QuestionCreateForm(forms.ModelForm):

  class Meta:
    model = Question
    fields = ['body', 'answer', 'status']

  def __init__(self, *args, **kwargs):
    super(QuestionCreateForm, self).__init__(*args, **kwargs)
    self.fields['body'].label = 'Question'
    self.fields['status'].label = 'Mark as Public'
    self.fields['body'].widget.attrs['readonly'] = True
    self.fields['body'].widget.attrs['rows'] = '1'


class NewQuestionForm(forms.ModelForm):
  class Meta:
    model = Question
    fields = ['body']

  def __init__(self, *args, **kwargs):
    super(NewQuestionForm, self).__init__(*args, **kwargs)
    self.fields['body'].label = 'your Question'


class ReAskQuestionForm(forms.ModelForm):
  class Meta:
    model = Question
    fields = ['receiver']

askfm/accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.shortcuts import render, redirect
from ..question.models import Question, Like
from .models import User, Friendship
from .forms import EditProfileForm, UserCreateForm
from django.views.generic import UpdateView


# friends page
def get_friends(request):
  current_user = User.objects.get(username=request.user)
  my_friends = Friendship.objects.filter(creator=current_user)
  friends = []
  for friend in my_friends:
    u = User.objects.get(username=friend.friend)
    friends.append(u)
  users = User.objects.all()
  unfriend_users = []
  for u in users:
    if u not in friends:
      unfriend_users.append(u)

  context = {
    'users': unfriend_users,
    'friends': friends,
    'current_user': current_user,
  }
  return render(request, 'accounts/friends.html', context)


# edit user profile
class Edit_profile(UpdateView):
  form_class = EditProfileForm
  template_name = 'accounts/edit_profile.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    users = User.objects.all()
    current_user = User.objects.get(username=self.request.user)
    my_friends = Friendship.objects.filter(creator=current_user)
    friends = []
    for friend in my_friends:
      u = User.objects.get(username=friend.friend)
      friends.append(u)
    unfriend_users = []
    for u in users:
      if u not in friends:
        unfriend_users.append(u)
    context['users'] = unfriend_users
    context['current_user'] = current_user
    return context

  def get_success_url(self):
    return reverse_lazy('accounts:my_profile', kwargs={'pk': self.kwargs['pk']})

  def get_object(self, queryset=None):
    obj = User.objects.get(id=self.kwargs['pk'])
    return obj


def my_profile(request, pk):
  user = User.objects.filter(id=pk)[0]
  questions = Question.objects.filter(status=True, receiver=user)
  likes = []
  like_count = 0
  quest_count = len(questions)
  for question in questions:
    like = Like.objects.filter(user=request.user, question=question)
    if like:
      likes.append(1)
      like_count += 1
    else:
      likes.append(0)
  mylist = zip(questions, likes)
  current_user = User.objects.get(username=request.user)

  your_friend = False
  friends = Friendship.objects.filter(creator=current_user)
  for ff in friends:
    if ff.friend == user:
      your_friend = True

  flag = True
  if user == current_user:
    flag = False

  context = {
    'your_friend': your_friend,
    'flag': flag,
    'questions': mylist,
    'like_count': like_count,
    'quest_count': quest_count,
    'user': user,
    'current_user': current_user,
  }

  return render(request, 'accounts/profile.html', context)


class Signup(CreateView):
  form_class = UserCreateForm
  success_url = reverse_lazy('accounts:login')
  template_name = 'accounts/signup.html'


def follow(request, pk):
  creator = User.objects.get(username=request.user)
  friend = User.objects.get(pk=pk)
  frindship = Friendship.objects.get_or_create(creator=creator, friend=friend)

  # redirect to the same page user in
  return redirect(request.META.get('HTTP_REFERER'))


def unfollow(request, pk):
  creator = User.objects.get(username=request.user)
  friend = User.objects.get(pk=pk)
  friendship = Friendship.objects.filter(creator=creator, friend=friend)
  friendship.delete()
  return redirect(request.META.get('HTTP_REFERER'))

askfm/question/views.py
from django.shortcuts import render, redirect
from .models import Question, Like
from ..accounts.models import User, Friendship
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
import datetime
from django.views.generic import UpdateView
from .forms import QuestionCreateForm, NewQuestionForm, ReAskQuestionForm


def reAsk_question(request, pk):
  question_body = Question.objects.get(id=pk).body,
  if request.method == 'POST':
    question_form = ReAskQuestionForm(request.POST, request.FILES)
    if question_form.is_valid():
      question = question_form.save(commit=False)
      question.sender = User.objects.get(username=request.user)
      question.body = question_body[0]
      question.save()
      return HttpResponseRedirect(reverse_lazy('question:home'))
  elif request.method == 'GET':
    form = ReAskQuestionForm()
    current_user = User.objects.get(username=request.user)
    users = User.objects.all()
    my_friends = Friendship.objects.filter(creator=current_user)
    friends = []
    for friend in my_friends:
      u = User.objects.get(username=friend.friend)
      friends.append(u)
    unfriend_users = []
    for u in users:
      if u not in friends:
        unfriend_users.append(u)
    context = {
      'form': form,
      'question': question_body[0],
      'current_user': current_user,
      'users': unfriend_users,
    }
    return render(request, 'question/re_ask_quest.html', context)


# ask new question

def add_question(request, pk):
  if request.method == 'POST':
    question_form = NewQuestionForm(request.POST, request.FILES)
    if question_form.is_valid():
      question = question_form.save(commit=False)
      question.sender = User.objects.get(username=request.user)
      question.receiver = User.objects.get(id=pk)
      question.save()
      return HttpResponseRedirect(reverse_lazy('question:add_question', kwargs={'pk': pk}))
  elif request.method == 'GET':
    form = NewQuestionForm()
    current_user = User.objects.get(username=request.user)
    users = User.objects.all()
    my_friends = Friendship.objects.filter(creator=current_user)
    friends = []
    for friend in my_friends:
      u = User.objects.get(username=friend.friend)
      friends.append(u)
    unfriend_users = []
    for u in users:
      if u not in friends:
        unfriend_users.append(u)
    context = {
      'form': form,
      'current_user': current_user,
      'users': unfriend_users,
    }
    return render(request, 'question/new_question.html', context)


class AnsQuestion(UpdateView):
  form_class = QuestionCreateForm
  template_name = 'question/ans_quest.html'
  success_url = reverse_lazy('question:quest')

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    current_user = User.objects.get(username=self.request.user)
    users = User.objects.all()
    my_friends = Friendship.objects.filter(creator=current_user)
    friends = []
    for friend in my_friends:
      u = User.objects.get(username=friend.friend)
      friends.append(u)
    unfriend_users = []
    for u in users:
      if u not in friends:
        unfriend_users.append(u)
    context['users'] = unfriend_users
    context['current_user'] = current_user
    return context

  def get_object(self, queryset=None):
    obj, created = Question.objects.get_or_create(id=self.kwargs['pk'])
    return obj


def quest_del(request, pk):
  question = Question.objects.get(id=pk)
  question.delete()
  return HttpResponseRedirect(reverse_lazy('question:quest'))


def quest(request):
  if request.user.is_authenticated:
    questions = Question.objects.filter(receiver=request.user, answer='')
    users = User.objects.all()
    current_user = User.objects.get(username=request.user)
    my_friends = Friendship.objects.filter(creator=current_user)
    friends = []
    for friend in my_friends:
      u = User.objects.get(username=friend.friend)
      friends.append(u)
    unfriend_users = []
    for u in users:
      if u not in friends:
        unfriend_users.append(u)
    context = {
      'questions': questions,
      'users': unfriend_users,
      'now': datetime.datetime.now(),
      'current_user': current_user,
    }
    return render(request, 'question/question.html', context)
  else:
    return redirect('/')


def home(request):
  if request.user.is_authenticated:
    current_user = User.objects.get(username=request.user)
    questions = Question.objects.filter(status=True)
    users = User.objects.all()

    likes = []
    users_images = []
    filtered_questions = []
    my_friends = Friendship.objects.filter(creator=current_user)
    friends = []
    for friend in my_friends:
      u = User.objects.get(username=friend.friend)
      friends.append(u)

    unfriend_users = []
    for u in users:
      if u not in friends:
        unfriend_users.append(u)

    for question in questions:
      user = question.receiver
      if user == current_user or user in friends:
        filtered_questions.append(question)

      question_user = User.objects.filter(username=user)[0]
      users_images.append(question_user)
      like = Like.objects.filter(user=request.user, question=question)
      if like:
        likes.append(1)
      else:
        likes.append(0)
    mylist = zip(filtered_questions, likes, users_images)
    context = {
      'questions': mylist,
      'users': unfriend_users,
      'current_user': current_user,
    }
    return render(request, 'question/home.html', context)
  else:
    return redirect('/')


def like_question(request, pk):
  user = User.objects.get(username=request.user)
  question = Question.objects.get(id=pk)
  question.likes = question.likes + 1
  like = Like.objects.get_or_create(user=user, question=question, value=True)

  # redirect to the same page user in
  return redirect(request.META.get('HTTP_REFERER'))


def dislike_question(request, pk):
  user = User.objects.get(username=request.user)
  question = Question.objects.get(id=pk)
  question.likes = question.likes - 1
  like = Like.objects.filter(user=user, question=question, value=True)
  like.delete()
  return redirect(request.META.get('HTTP_REFERER'))

askfm/templates/askfm.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AskFm Website</title>
  <!-- font awsome -->
  <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/all.css'
        integrity='sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU'
        crossorigin='anonymous'>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/style_accounts.css' %}">
</head>
<body style="background-color: white">
  <div class="container">
    <div class="row row-head">
      <h1>
        <a href="{% url 'root' %}"><span><strong>ask</strong></span>fm
        </a>
      </h1>
    </div>
    <div class="row row-body">
      <div class="col-md-4">
        <br>
        <img src="{% static 'imgs/eye.gif' %}">
        <br><br>
        Curious? <strong>Just ask!</strong>
        <br>
        <strong>Openly or anonymously.</strong>
        <br><br>
        <a href="{% url 'accounts:signup'  %}" class="bt1">Sign up</a>
        <br><br>
        <a href="{% url 'accounts:login' %}" class="bt2">Log in</a>
        <br><br><br>
      </div>
    </div>
    <div class="row footer">
      <ul>
        <li><a href="https://www.facebook.com/askfmpage"><i class="fab fa-facebook-f"></i></a></li>
        <li><a href="https://instagram.com/askfm"><i class="fab fa-instagram"></i></a></li>
        <li><a href="https://twitter.com/askfm"><i class="fab fa-twitter"></i></a></li>
        <li><a href="https://vk.com/askfm"><i class="fab fa-vk"></i></a></li>
        <li>© Ask.fm 2018</li>
      </ul>
    </div>
  </div>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

askfm/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load staticfiles %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %} AskFm Website {% endblock %}</title>
  <!-- font awsome -->
  <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/all.css'
        integrity='sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU'
        crossorigin='anonymous'>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  {% include 'navbar.html' %}
  <hr style="border: .2px solid #000000; margin: 0">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        {% block profile_content %}
        {% endblock %}
      </div>
      <div class="col-md-8">
        {% block content %}
        {% endblock %}
      </div>
      <div class="col-md-4">
        {% block sideContent %}
        {% endblock %}
      </div>
    </div>
  </div>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
  {% block js %}
  {% endblock %}
</body>
</html>

askfm/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light"
     style="background-color: #2F353A; padding: 0 0 0 4%;">
  <a class="navbar-brand" style="color: #FF643C;font-size: 25px;
     font-weight: bold; font-style: italic; margin: 0; " href="{% url 'question:home' %}">
      <span style="font-size: 40px;">ask</span>fm
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nn nav-link" href="{% url 'question:home' %}">
          <i title="feed" class='active fas fa-home'></i>
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'question:quest' %}" class="nn nav-link">
          <i title="Questions" class='fas fa-question-circle'></i>
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'accounts:my_profile' request.user.id %}" class="nn nav-link">
          <i title="profile" class='fas fa-user-circle'></i>
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'accounts:get_friends' %}" class="nn nav-link">
          <i title="friends" class='fas fa-user-friends'></i>
        </a>
      </li>
      <li class="nav-item">
        <a href="#" class="nn nav-link">
          <i title="Notifications" class="fa fa-fire"></i>
        </a>
      </li>
      <li class="nav-item">
        <a href="#" class="nn nav-link">
          <i title="settings" class="fa fa-cog"></i>
        </a>
      </li>
      <li class="nav-item">
        <a style="font-size: 25px; color: #FF643C"
           href="{% url 'accounts:my_profile' request.user.id %}" class="nav-link">

          <img src="{% if current_user.image %}
                      {{ current_user.image.url }}
                    {% else %}
                      {% static 'imgs/default.jpg' %}
                    {% endif %}" style="width: 50px; height: 50px; border-radius: 50%;"
          name="{{ request }}">
          {{ request.user.username }}
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'accounts:logout' %}" class="nn nav-link">
          <i title="Logout" class="fas fa-sign-out-alt"></i>
        </a>
      </li>
    </ul>
  </div>
</nav>