askfm/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_view
from . import views as core_view

app_name = 'accounts'

urlpatterns = [
  url(r'^login/$', auth_view.LoginView.as_view(template_name='accounts/login.html'), name='login'),
  url(r'^logout/$', auth_view.LogoutView.as_view(), name='logout'),
  url(r'^signup/$', core_view.Signup.as_view(), name='signup'),
  url(r'^profile/(?P<pk>\d+)$', core_view.my_profile, name='my_profile'),
  url(r'^edit-profile/(?P<pk>\d+)$', core_view.Edit_profile.as_view(), name='edit_profile'),
  url(r'my-friends/$', core_view.get_friends, name='get_friends'),
  url(r'^follow/(?P<pk>\d+)/$', core_view.follow, name='follow'),
  url(r'^unfollow/(?P<pk>\d+)/$', core_view.unfollow, name='unfollow'),
]

askfm/question/urls.py
from django.conf.urls import url
from . import views

app_name = 'question'

urlpatterns = [
  url(r'^home$', views.home, name='home'),
  url(r'^ans_quest/(?P<pk>\d+)$', views.AnsQuestion.as_view(), name='Ans_question'),
  url(r'^del/(?P<pk>\d+)$', views.quest_del, name='quest_del'),
  url(r'^question$', views.quest, name='quest'),
  url(r'^like_question/(?P<pk>\d+)/$', views.like_question, name='like_question'),
  url(r'^dislike_question/(?P<pk>\d+)/$', views.dislike_question, name='dislike_question'),
  url(r'^add_question/(?P<pk>\d+)/$', views.add_question, name='add_question'),
  url(r'^re_ask_question/(?P<pk>\d+)/$', views.reAsk_question, name='re_ask_question'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from .views import root


urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('askfm.accounts.urls')),
  path('', root, name='root'),
  path('', include('askfm.question.urls')),
  url(r'^oauth/', include('social_django.urls', namespace='social')),
  path('tinymce/', include('tinymce.urls')),
  url('avatar/', include('avatar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

askfm/question/models.py
from django.db import models
from django.utils import timezone
from ..accounts.models import User


# Question Model
class Question(models.Model):

  sender = models.ForeignKey(User, related_name='senders', on_delete=models.CASCADE)
  body = models.TextField()
  receiver = models.ForeignKey(User, related_name='recievers', on_delete=models.CASCADE)
  answer = models.TextField(default='', blank=True)
  publish = models.DateTimeField(default=timezone.now)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)
  status = models.BooleanField(default=False)
  likes = models.IntegerField(default=0)

  class Meta:
    ordering = ('-updated',)

  def __str__(self):
    return str(self.id)


# Like Model
class Like(models.Model):

  user = models.ForeignKey(User, related_name='user_likes', on_delete=models.CASCADE)
  question = models.ForeignKey(Question, related_name='liked_questions', on_delete=models.CASCADE)
  value = models.BooleanField(default=False)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)

  def __str__(self):
    return str(self.user) + ':' + str(self.question) + ':' + str(self.value)

askfm/question/forms.py
from django import forms
from .models import Question


class QuestionCreateForm(forms.ModelForm):

  class Meta:
    model = Question
    fields = ['body', 'answer', 'status']

  def __init__(self, *args, **kwargs):
    super(QuestionCreateForm, self).__init__(*args, **kwargs)
    self.fields['body'].label = 'Question'
    self.fields['status'].label = 'Mark as Public'
    self.fields['body'].widget.attrs['readonly'] = True
    self.fields['body'].widget.attrs['rows'] = '1'


class NewQuestionForm(forms.ModelForm):
  class Meta:
    model = Question
    fields = ['body']

  def __init__(self, *args, **kwargs):
    super(NewQuestionForm, self).__init__(*args, **kwargs)
    self.fields['body'].label = 'your Question'


class ReAskQuestionForm(forms.ModelForm):
  class Meta:
    model = Question
    fields = ['receiver']

askfm/question/views.py
from django.shortcuts import render, redirect
from .models import Question, Like
from ..accounts.models import User, Friendship
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
import datetime
from django.views.generic import UpdateView
from .forms import QuestionCreateForm, NewQuestionForm, ReAskQuestionForm


def reAsk_question(request, pk):
  question_body = Question.objects.get(id=pk).body,
  if request.method == 'POST':
    question_form = ReAskQuestionForm(request.POST, request.FILES)
    if question_form.is_valid():
      question = question_form.save(commit=False)
      question.sender = User.objects.get(username=request.user)
      question.body = question_body[0]
      question.save()
      return HttpResponseRedirect(reverse_lazy('question:home'))
  elif request.method == 'GET':
    form = ReAskQuestionForm()
    current_user = User.objects.get(username=request.user)
    users = User.objects.all()
    my_friends = Friendship.objects.filter(creator=current_user)
    friends = []
    for friend in my_friends:
      u = User.objects.get(username=friend.friend)
      friends.append(u)
    unfriend_users = []
    for u in users:
      if u not in friends:
        unfriend_users.append(u)
    context = {
      'form': form,
      'question': question_body[0],
      'current_user': current_user,
      'users': unfriend_users,
    }
    return render(request, 'question/re_ask_quest.html', context)


# ask new question

def add_question(request, pk):
  if request.method == 'POST':
    question_form = NewQuestionForm(request.POST, request.FILES)
    if question_form.is_valid():
      question = question_form.save(commit=False)
      question.sender = User.objects.get(username=request.user)
      question.receiver = User.objects.get(id=pk)
      question.save()
      return HttpResponseRedirect(reverse_lazy('question:add_question', kwargs={'pk': pk}))
  elif request.method == 'GET':
    form = NewQuestionForm()
    current_user = User.objects.get(username=request.user)
    users = User.objects.all()
    my_friends = Friendship.objects.filter(creator=current_user)
    friends = []
    for friend in my_friends:
      u = User.objects.get(username=friend.friend)
      friends.append(u)
    unfriend_users = []
    for u in users:
      if u not in friends:
        unfriend_users.append(u)
    context = {
      'form': form,
      'current_user': current_user,
      'users': unfriend_users,
    }
    return render(request, 'question/new_question.html', context)


class AnsQuestion(UpdateView):
  form_class = QuestionCreateForm
  template_name = 'question/ans_quest.html'
  success_url = reverse_lazy('question:quest')

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    current_user = User.objects.get(username=self.request.user)
    users = User.objects.all()
    my_friends = Friendship.objects.filter(creator=current_user)
    friends = []
    for friend in my_friends:
      u = User.objects.get(username=friend.friend)
      friends.append(u)
    unfriend_users = []
    for u in users:
      if u not in friends:
        unfriend_users.append(u)
    context['users'] = unfriend_users
    context['current_user'] = current_user
    return context

  def get_object(self, queryset=None):
    obj, created = Question.objects.get_or_create(id=self.kwargs['pk'])
    return obj


def quest_del(request, pk):
  question = Question.objects.get(id=pk)
  question.delete()
  return HttpResponseRedirect(reverse_lazy('question:quest'))


def quest(request):
  if request.user.is_authenticated:
    questions = Question.objects.filter(receiver=request.user, answer='')
    users = User.objects.all()
    current_user = User.objects.get(username=request.user)
    my_friends = Friendship.objects.filter(creator=current_user)
    friends = []
    for friend in my_friends:
      u = User.objects.get(username=friend.friend)
      friends.append(u)
    unfriend_users = []
    for u in users:
      if u not in friends:
        unfriend_users.append(u)
    context = {
      'questions': questions,
      'users': unfriend_users,
      'now': datetime.datetime.now(),
      'current_user': current_user,
    }
    return render(request, 'question/question.html', context)
  else:
    return redirect('/')


def home(request):
  if request.user.is_authenticated:
    current_user = User.objects.get(username=request.user)
    questions = Question.objects.filter(status=True)
    users = User.objects.all()

    likes = []
    users_images = []
    filtered_questions = []
    my_friends = Friendship.objects.filter(creator=current_user)
    friends = []
    for friend in my_friends:
      u = User.objects.get(username=friend.friend)
      friends.append(u)

    unfriend_users = []
    for u in users:
      if u not in friends:
        unfriend_users.append(u)

    for question in questions:
      user = question.receiver
      if user == current_user or user in friends:
        filtered_questions.append(question)

      question_user = User.objects.filter(username=user)[0]
      users_images.append(question_user)
      like = Like.objects.filter(user=request.user, question=question)
      if like:
        likes.append(1)
      else:
        likes.append(0)
    mylist = zip(filtered_questions, likes, users_images)
    context = {
      'questions': mylist,
      'users': unfriend_users,
      'current_user': current_user,
    }
    return render(request, 'question/home.html', context)
  else:
    return redirect('/')


def like_question(request, pk):
  user = User.objects.get(username=request.user)
  question = Question.objects.get(id=pk)
  question.likes = question.likes + 1
  like = Like.objects.get_or_create(user=user, question=question, value=True)

  # redirect to the same page user in
  return redirect(request.META.get('HTTP_REFERER'))


def dislike_question(request, pk):
  user = User.objects.get(username=request.user)
  question = Question.objects.get(id=pk)
  question.likes = question.likes - 1
  like = Like.objects.filter(user=user, question=question, value=True)
  like.delete()
  return redirect(request.META.get('HTTP_REFERER'))

askfm/question/templates/question/ans_quest.html
{% extends 'base.html' %}
{% load static %}
<style>
  textarea[name='body']{
    border: none;
    outline: none;
    padding-left: 50px;
    font-size: 25px;
    text-align: center;
  }
</style>
{% block title %}
  Feed | AskFm
{% endblock %}

{% block content %}
  <div style="background-color: white; text-align: center">
    <h2 style="padding-top: 20px; color: #FF643C">Answer the Question</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
        <p>
          <h5 style="margin: 0; padding: 0;">{{ field.label_tag }}</h5>
          {{ field}}
          {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        </p>
      {% endfor %}
      <button type="submit">
        <i class="fas fa-location-arrow"></i>
      </button>
    </form>
    <br>
  </div>
{% endblock %}

{% block sideContent %}
  {% include 'question/sideContent.html' %}
{% endblock %}

{% block js %}
  <script>
    $(document).ready(function(){
      let x = document.getElementById('id_body');
      let l = x.textContent.length;
      l = l/50 + 1;
      x.rows = ""+l;
    });
  </script>
{% endblock %}

askfm/question/templates/question/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Feed | AskFm
{% endblock %}

{% block content %}
 {% for q in questions %}
    <div class="con">
      <h3 style="padding: 20px;">{{q.0.body}}</h3>
      <br>
      <span style="margin-left: 20px;">
        <a style="text-decoration: none" href="{% url 'accounts:my_profile' q.2.pk %}">
          <img src="{% if q.2.image %}
                      {{ q.2.image.url }}
                    {% else %}
                      {% static 'imgs/default.jpg' %}
                    {% endif %}" style="width: 50px; height: 50px; border-radius: 50%;">
        </a>
      </span>
      <span style="padding: 20px; font-size: 20px; color: #CEC4D7">
        {{q.0.receiver}} . {{q.0.updated|timesince}}
      </span>
      <br>
      <h4 style="padding: 20px;">{{q.0.answer}}</h4>
      <div style="height: 50px;">
      {% if q.1 == 1 %}
        <a class="like_dis" href="{% url 'question:dislike_question' q.0.id %}" >
          <span style="margin-left: 20px; font-size: 36px; color: #FF643C;">
            <i class='fas fa-heart'></i>
          </span>
        </a>
      {% else %}
        <a title="Like" class="like_dis" href="{% url 'question:like_question' q.0.id %}" >
          <span style="margin-left: 20px; font-size: 36px; color: #CEC4D7;">
            <i class='fas fa-heart'></i>
          </span>
        </a>
      {% endif %}
       <a title="Re ask" style="float: right" href="{% url 'question:re_ask_question' q.0.id %}">
          <span style=" float: right; margin-right: 20px; font-size: 36px; color: #CEC4D7;">
            <i class='fas fa-recycle'></i>
          </span>
       </a>
      </div>
      <hr style="border: 7px solid #CEC4D7; margin: 0">
    </div>
  {% endfor %}
{% endblock %}

{% block sideContent %}
  {% include 'question/sideContent.html' %}
{% endblock %}

askfm/question/templates/question/new_question.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Feed | AskFm
{% endblock %}

{% block content %}
  <div style="background-color: white; padding: 20px;">
    <h2 style="padding: 20px 20px">ask a question</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
        <p>
          {{ field }}
          {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        </p>
      {% endfor %}
      <button style="margin-left: 330px;" type="submit">
        <i class="fas fa-location-arrow"></i>
      </button>
    </form>
  </div>
{% endblock %}

{% block sideContent %}
  {% include 'question/sideContent.html' %}
{% endblock %}

askfm/question/templates/question/question.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Feed | AskFm
{% endblock %}

{% block content %}
 {% for q in questions %}
    <div class="con1">
      <h3>{{q.body}}</h3>
      <a href="{% url 'question:quest_del' q.id %}"><i class="fas fa-trash-alt"></i></a>
      <br>
      <span style="padding: 20px; font-size: 20px; color: #CEC4D7">
        {{q.created|timesince}}
      </span>
      <a class="ans" href="{% url 'question:Ans_question' q.id %}">Answer > </a>
      <br><br>
      <hr style="border: 7px solid #CEC4D7; margin:0;">
    </div>
  {% endfor %}
{% endblock %}

{% block sideContent %}
  {% include 'question/sideContent.html' %}
{% endblock %}

{% block js %}
  <script>
    $(document).ready(function(){
      var x = document.getElementsByTagName('i');
      $(x[0]).removeClass("active");
      $(x[1]).addClass("active");
    });
  </script>
{% endblock %}

askfm/question/templates/question/re_ask_quest.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Feed | AskFm
{% endblock %}

{% block content %}
  <div style="background-color: white; padding: 20px;">
    <h2 style="padding: 20px 20px">Re ask a question</h2>
    <h3 style="padding: 10px 20px;">{{ question }}</h3>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
        <p style="display: inline-block;">
          <span style="padding: 10px 20px;font-size: 20px;">{{ field.label_tag }}</span>
          {{ field }}
          {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        </p>
      {% endfor %}
      <button style="float: right;" type="submit">
        <i class="fas fa-location-arrow"></i>
      </button>
    </form>
  </div>
{% endblock %}

{% block sideContent %}
  {% include 'question/sideContent.html' %}
{% endblock %}

askfm/question/templates/question/sideContent.html
{% load static %}
  <br>
  <h5 style="color: #929497">Users</h5>
  {% for u in users %}
    <div class="sid_user">
      <a style="text-decoration: none;" href="{% url 'accounts:my_profile' u.pk %}">
        <span style="margin-left: 20px;">
          <img src="{% if u.image %}
                      {{ u.image.url }}
                    {% else %}
                      {% static 'imgs/default.jpg' %}
                    {% endif %}" style="width: 50px; height: 50px; border-radius: 50%;">
        </span>
        <span style="padding: 20px; font-size: 20px;">{{u.username}}</span>
      </a>
      {% if u != current_user %}
        <a href="{% url 'accounts:follow' u.pk %}" title="follow" class="ask_user">
          <i class="fas fa-user-plus"></i>
        </a>
      {% endif %}
      <a class="ask_user" href="{% url 'question:add_question' u.pk %}">Ask ></a>
      <hr style="border: .4px solid #4F5458; margin: 0">
    </div>
  {% endfor %}